global:
  owner: crmadrig@tibco.com
  qsname: bwce-cf-quickstart
  #s3bucket: projectx-templates <- (Optional) Only needed if you want to use a specific bucket
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-central-1
    - eu-west-1

  reporting: true
tests:
  # The following test will test in us-east-1 using sample-cloudformation-input.json as inputs
  scenario-1:
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-central-1
      - eu-west-1
    parameter_input: bwce-cloudformation-input-withvpc.json
    template_file: bwce-cloudformation-project-withvpc.template
